spring.application.name=crudDemo
spring.datasource.url=jdbc:postgresql://localhost:5432/studentdb
spring.datasource.username=postgres
spring.datasource.password=Namdev@6266
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true